title: Giovanni Colucci
description: POLIMI
url: https://github.com/coluccigiovanni16
author: Giovanni Colucci
permalink: pretty

exclude:
  - Gemfile
  - LICENSE
  - README.md
  - vendor/
  - cv.aux
  - cv.fdb_latexmk
  - cv.fls
  - cv.log
  - cv.out
  - cv.synctex.gz

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap


